### ISSUE TITLE
Implementation of MPII set

### ISSUE THREAD

**Issue by wangdong0556** [yangsenius/TransPose#18]
Hello ,
    I am very happy to see such excellent work. How can I use this project to train and test in MPII? I adjusted some parameters, but the result is not very good. Have you done any work on this data set?

   In addition, what is the basis for determining the number of heads for different models? 

Thank you!

**Comment by yangsenius** [comment]
Thanks for your interest!

This repo is based on DarkPose. You only need to change some configs of experiment Yaml files for MPII. See [darkpose](https://github.com/ilovepose/DarkPose/blob/master/experiments/mpii/hrnet/w32_256x256_adam_lr1e-3.yaml) for reference.

I adjust the number of heads according to the dimension of query key vectors, in order to keep the dimension in each head not very large. 

For ResNet, d=256, then `n_heads = 8 = 256 // 32`. For HRNet, d=96, then `n_heads = 1 = 96 // 64`.

Also, for hrnet, using fewer heads is to consume less GPU memory.

**Comment by wangdong0556** [comment]
“For ResNet-S based, d=256, then n_heads = 8 = 256 // 32. For HRNet-S based, d=96, then n_heads = 1 = 96 // 96.”
The values of RESNET and HRNet are 32 and 96 respectively. What are the meanings of these values（32 and 96）? Are they 96 for hrnet-s-w32 and w48?

**Comment by yangsenius** [comment]
Actually, they have no special meanings. 64 for HRNet-W32, 96 for HRNet-w48

**Comment by yangsenius** [comment]
The output feature map channel for ResNet is 512, so we set the d_model to be 256; The output feature map channel for HRNet is 32 or 48, so we set the d_model to be 64 or 96.

**Comment by wangdong0556** [comment]
Thanks！Why is the d_model  set to one-half of the output feature map channel, is it a fixed setting or is there some other reason?

**Comment by yangsenius** [comment]
There is no special reasons for halving or doubling the channels. We want the channel transformation to be of the same order of magnitude.
